theme: minima

permalink: pretty
lang: en-AU
title: Alistair's Chest
description: Game description goes here.
url: https://alistairschest.com
author:
  name: Overgrowth Studio
twitter_username: OvergrowthAU

github:
  is_project_page: false